services:
  webapp:
    image: ${DOCKER_IMAGE:-ghcr.io/rrhul0/future-capsule:latest}
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - TZ=${TZ}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - GITLAB_ID=${GITLAB_ID}
      - GITLAB_SECRET=${GITLAB_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - BREVO_USER=${BREVO_USER}
      - BREVO_PASS=${BREVO_PASS}
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${BRANCH_NAME}.entrypoints=websecure'
      - 'traefik.http.routers.${BRANCH_NAME}.rule=Host(`${DEPLOYMENT_DOMAIN}`)'
      - 'traefik.http.routers.${BRANCH_NAME}.tls.certresolver=myresolver'
      - 'traefik.http.services.${BRANCH_NAME}.loadbalancer.server.port=3000'

  worker:
    image: ${WORKER_IMAGE:-ghcr.io/rrhul0/future-capsule-worker:latest}
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - BREVO_USER=${BREVO_USER}
      - BREVO_PASS=${BREVO_PASS}
      - TZ=${TZ}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: future-capsule
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  default:
    external: true
    name: traefik

volumes:
  postgres:
  redis:
