services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: future-capsule
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  default:
    name: traefik
    external: true

volumes:
  postgres:
  redis:
