services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: future-capsule
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  default:
    name: traefik
    external: true

volumes:
  postgres:
  redis:
