name: Deploy App

on:
  push:
    branches:
      - main
      - '**'

env:
  REGISTRY: ghcr.io
  APP_NAME: future-capsule

# concurrency:
#   group: preview
#   cancel-in-progress: true

jobs:
  pre-setup:
    runs-on: self-hosted
    environment: preview
    concurrency: preview
    outputs:
      postgres_ip: ${{ steps.db-setup.outputs.postgres_ip }}
      redis_ip: ${{ steps.db-setup.outputs.redis_ip }}
    steps:
      - name: Download the docker compose for application from GitHub
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          curl -o docker-compose.db.yml -L https://raw.githubusercontent.com/rrhul0/future-capsule/$BRANCH_NAME/docker-compose.db.yml

      - name: Run databases if not running
        id: db-setup
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          IMAGE_TAG=$([[ "$BRANCH_NAME" == "main" ]] && echo "latest" || echo "$BRANCH_NAME")

          if [ ! "$(docker ps -q -f name=$APP_NAME-$IMAGE_TAG-db-postgres-1)" ]; then
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASS }} \
            docker compose --project-name $APP_NAME-$IMAGE_TAG-db -f docker-compose.db.yml up -d postgres
          fi

          if [ ! "$(docker ps -q -f name=$APP_NAME-$IMAGE_TAG-db-redis-1)" ]; then
            docker compose --project-name $APP_NAME-$IMAGE_TAG-db -f docker-compose.db.yml up -d redis
          fi

          POSTGRES_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $APP_NAME-$IMAGE_TAG-db-postgres-1)
          echo "POSTGRES_IP=$POSTGRES_IP" >> $GITHUB_OUTPUT
          REDIS_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $APP_NAME-$IMAGE_TAG-db-redis-1)
          echo "REDIS_IP=$REDIS_IP" >> $GITHUB_OUTPUT

          echo "POSTGRES_IP=$POSTGRES_IP"
          echo "REDIS_IP=$REDIS_IP"

  build:
    runs-on: ubuntu-24.04-arm
    needs: pre-setup
    environment: preview
    concurrency: preview
    permissions:
      contents: read
      packages: write
      id-token: write # Important for at least docker gha cache

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Build and Push Docker Image
        env:
          POSTGRES_IP: ${{needs.pre-setup.outputs.postgres_ip}}
          REDIS_IP: ${{needs.pre-setup.outputs.redis_ip}}
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          IMAGE_TAG=$([[ "$BRANCH_NAME" == "main" ]] && echo "latest" || echo "$BRANCH_NAME")

          NEXT_PUBLIC_APP_URL=$([[ "$BRANCH_NAME" == "main" ]] && echo "https://prod.tt.clammy.xyz" || echo "https://${BRANCH_NAME}.tt.clammy.xyz")
          AUTH_URL=$NEXT_PUBLIC_APP_URL/auth

          DATABASE_URL_BUILD=postgresql://postgres:${{ secrets.POSTGRES_PASS }}@$POSTGRES_IP:5432/$APP_NAME?schema=public
          REDIS_URL_BUILD=redis://$REDIS_IP:6379

          echo $POSTGRES_IP
          echo $REDIS_IP
          echo $DATABASE_URL_BUILD
          echo $REDIS_URL_BUILD

          docker pull $REGISTRY/$GITHUB_ACTOR/$APP_NAME:$IMAGE_TAG || true

          docker buildx create --name mybuilder --driver docker-container --use

          docker buildx build --builder mybuilder --load \
          --cache-from=type=registry,ref=$REGISTRY/$GITHUB_ACTOR/$APP_NAME:cache \
          --cache-to=type=registry,ref=$REGISTRY/$GITHUB_ACTOR/$APP_NAME:cache,mode=max \
          --build-arg DATABASE_URL=$DATABASE_URL_BUILD \
          --build-arg REDIS_URL=$REDIS_URL_BUILD \
          --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
          --build-arg TZ=${{ vars.TZ }} \
          --build-arg GITHUB_ID=${{ vars.GH_ID }} \
          --build-arg GITHUB_SECRET=${{ secrets.GH_SECRET }} \
          --build-arg GOOGLE_ID=${{ vars.GOOGLE_ID }} \
          --build-arg GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
          --build-arg GITLAB_ID=${{ vars.GITLAB_ID }} \
          --build-arg GITLAB_SECRET=${{ secrets.GITLAB_SECRET }} \
          --build-arg AUTH_URL=$AUTH_URL \
          --build-arg NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }} \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }} \
          --build-arg BREVO_USER=${{ secrets.BREVO_USER }} \
          --build-arg BREVO_PASS=${{ secrets.BREVO_PASS }} \
          -t $REGISTRY/$GITHUB_ACTOR/$APP_NAME:$IMAGE_TAG --file Dockerfile .

          docker push $REGISTRY/$GITHUB_ACTOR/$APP_NAME:$IMAGE_TAG

  deploy:
    needs: build
    environment: preview
    concurrency: preview
    permissions:
      contents: read
      packages: read
    runs-on: self-hosted

    steps:
      - name: Login to GitHub Container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Download the docker compose for application from GitHub
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          curl -o docker-compose.yml -L https://raw.githubusercontent.com/rrhul0/future-capsule/$BRANCH_NAME/docker-compose.yml

      - name: Set up environment variables and deploy the docker image
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          IMAGE_TAG=$([[ "$BRANCH_NAME" == "main" ]] && echo "latest" || echo "$BRANCH_NAME")

          AUTH_URL=$([[ "$BRANCH_NAME" == "main" ]] && echo "https://prod.tt.clammy.xyz/auth" || echo "https://${BRANCH_NAME}.tt.clammy.xyz/auth")
          NEXT_PUBLIC_APP_URL=$([[ "$BRANCH_NAME" == "main" ]] && echo "https://prod.tt.clammy.xyz" || echo "https://${BRANCH_NAME}.tt.clammy.xyz")
          DATABASE_URL=postgresql://postgres:${{ secrets.POSTGRES_PASS }}@$APP_NAME-$IMAGE_TAG-db-postgres-1:5432/$APP_NAME?schema=public

          docker pull $REGISTRY/$GITHUB_ACTOR/$APP_NAME:$IMAGE_TAG

          if [ "$(docker ps -q -f name=$APP_NAME-$IMAGE_TAG-app-webapp-1)" ]; then
            docker compose --project-name $APP_NAME-$IMAGE_TAG-app down
          fi

          DATABASE_URL=${{ secrets.DATABASE_URL}} \
          REDIS_URL=${{ vars.REDIS_URL }} \
          AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
          TZ=${{ vars.TZ }} GITHUB_ID=${{ vars.GH_ID}} \
          GOOGLE_ID=${{ vars.GOOGLE_ID}} \
          GITLAB_ID=${{ vars.GITLAB_ID}} \
          GITHUB_SECRET=${{ secrets.GH_SECRET}} \
          GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET}} \
          GITLAB_SECRET=${{ secrets.GITLAB_SECRET}} \
          AUTH_URL=$AUTH_URL \
          NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
          NEXT_PUBLIC_FIREBASE_API_KEY=${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY}} \
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}} \
          NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID}} \
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}} \
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}} \
          NEXT_PUBLIC_FIREBASE_APP_ID=${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID}} \
          BREVO_USER=${{ secrets.BREVO_USER}} \
          BREVO_PASS=${{ secrets.BREVO_PASS}} \
          IMAGE_TAG=$IMAGE_TAG \
          docker compose --project-name $APP_NAME-$IMAGE_TAG-app up -d
