name: Deploy App

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: debug variables
        run: |
          vars
          env
