name: Deploy App

on:
  push:
    branches:
      - main
      - '**' # All branches for preview deployment

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rrhul0/future-capsule

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker Image
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          IMAGE_TAG=$([[ "$BRANCH_NAME" == "main" ]] && echo "latest" || echo "$BRANCH_NAME")

          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Deploy Application
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          COMPOSE_FILE=$([[ "$BRANCH_NAME" == "main" ]] && echo "docker-compose.production.yml" || echo "docker-compose.preview.yml")

          docker pull $REGISTRY/$IMAGE_NAME:$BRANCH_NAME
          docker-compose -f $COMPOSE_FILE up -d
